// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(EvidencijaContext))]
    partial class EvidencijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Server.Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lokacija");

                    b.Property<int>("MaxUcesnici")
                        .HasColumnType("int")
                        .HasColumnName("Maksimalni_Broj_Učesnika");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("PobednikID")
                        .HasColumnType("int")
                        .HasColumnName("Pobednik");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int")
                        .HasColumnName("TurnirID");

                    b.HasKey("ID");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("Server.Models.Turnir", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("MaxDisciplina")
                        .HasColumnType("int")
                        .HasColumnName("MaxDisciplina");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Turnir");
                });

            modelBuilder.Entity("Server.Models.Ucesnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Brzina")
                        .HasColumnType("int")
                        .HasColumnName("Brzina");

                    b.Property<bool?>("Compete")
                        .HasColumnType("bit")
                        .HasColumnName("Compete");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("int")
                        .HasColumnName("DisciplinaID");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime");

                    b.Property<int?>("Pozicija")
                        .HasColumnType("int")
                        .HasColumnName("Pozicija");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prezime");

                    b.Property<int?>("Rang")
                        .HasColumnType("int")
                        .HasColumnName("Rang");

                    b.Property<bool?>("Selected")
                        .HasColumnType("bit")
                        .HasColumnName("Selected");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int")
                        .HasColumnName("TurnirID");

                    b.HasKey("ID");

                    b.ToTable("Učesnik");
                });
#pragma warning restore 612, 618
        }
    }
}
